/** @type {import('tailwindcss').Config} */
// Tokens mirror the Stitch "Editorial Minimalism" design system (DESIGN.md).
export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#8ad5be",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#7d2d0a",
        "surface-bright": "#fbf9f3",
        "surface-dim": "#dcdad4",
        secondary: "#186a57",
        "on-secondary-fixed": "#002019",
        "tertiary-container": "#747479",
        error: "#ba1a1a",
        "on-surface-variant": "#56423c",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#9c4420",
        "secondary-fixed": "#a5f2d9",
        "inverse-surface": "#30312d",
        surface: "#fbf9f3",
        "tertiary-fixed-dim": "#c7c6cb",
        "secondary-container": "#a5f2d9",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdbcf",
        "on-primary-fixed": "#380d00",
        "tertiary-fixed": "#e3e2e8",
        "surface-container-low": "#f5f3ed",
        "surface-container-highest": "#e4e2dd",
        "on-tertiary-container": "#fefcff",
        "primary-container": "#b85933",
        "surface-container": "#f0eee8",
        tertiary: "#5b5b61",
        "on-secondary-container": "#21705d",
        primary: "#99411e",
        outline: "#89726a",
        "on-error": "#ffffff",
        "on-background": "#1b1c18",
        background: "#fbf9f3",
        "primary-fixed-dim": "#ffb59b",
        "inverse-on-surface": "#f3f1eb",
        "on-surface": "#1b1c18",
        "surface-container-high": "#eae8e2",
        "surface-variant": "#e4e2dd",
        "inverse-primary": "#ffb59b",
        "on-secondary-fixed-variant": "#005141",
        "outline-variant": "#dcc1b8",
        "on-tertiary-fixed": "#1a1b20",
        "on-tertiary-fixed-variant": "#46464b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "max-width": "1200px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "max-width": "1200px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-md": ["Playfair Display", "Georgia", "serif"],
        "body-sm": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "data-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "display-lg": ["Playfair Display", "Georgia", "serif"],
        "body-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-sm": ["Playfair Display", "Georgia", "serif"],
        "display-lg-mobile": ["Playfair Display", "Georgia", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
